name: Publish Extension

# This workflow triggers whenever you push a new tag starting with "v" (e.g., v1.0.0)
on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Setup Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        with:
          node-version: 24.19.0
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      # (Optional) Run tests before publishing
      # - name: Run tests
      #   run: npm test

      # Publishes to the official VS Code Marketplace
      - name: Publish to Visual Studio Marketplace
        uses: HaaLeo/publish-vscode-extension@ca5561daa085dee804bf9f37fe0165785a9b14db # v2
        with:
          pat: ${{ secrets.VS_MARKETPLACE_TOKEN }}
          registryUrl: https://marketplace.visualstudio.com

      # (Optional) Publishes to Open VSX Registry
      - name: Publish to Open VSX Registry
        uses: HaaLeo/publish-vscode-extension@ca5561daa085dee804bf9f37fe0165785a9b14db # v2
        with:
          pat: ${{ secrets.OPEN_VSX_TOKEN }}